config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  extend FriendlyId
  
  HASHTAG_REGEXP = /#[[:word:]-]+/

  validates :name, presence: true, uniqueness: true

  has_many :hashtag_questions, dependent: :destroy
  has_many :questions, through: :hashtag_questions
  
  scope :sorted, -> { order(name: :asc) }

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.transliterate(:russian).normalize.to_s
  end
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  validates :text, presence: true, length: { maximum: 255 }

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions, dependent: :destroy

  after_commit :get_hashtags, on: %i[create update]
  after_destroy :remove_unrelated_hashtags

  private

  def get_hashtags
    self.hashtags =
      "#{text} #{answer}".
      downcase.
      scan(Hashtag::HASHTAG_REGEXP).
      uniq.
      map { |hashtag| Hashtag.find_or_create_by(name: hashtag) }
  end

  def remove_unrelated_hashtags
    Hashtag.includes(:questions).where(questions: { id: nil }).destroy_all
  end
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  extend FriendlyId

  EMAIL_VALIDATION_REGEXP = /.+@.+\..+/i
  USERNAME_VALIDATION_REGEXP = /\A[A-Za-z0-9_]+\z/
  HEADER_COLOR_VALIDATION = /\A[0-9A-F]{6}\z/
  AVATAR_URL_VALIDATION = /(https?:\/\/.*\.(?:png|jpg|webp|gif))/
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  attr_accessor :password

  validates :username, presence: true, uniqueness: true, format: { with: USERNAME_VALIDATION_REGEXP }, length: { maximum: 40 }
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_VALIDATION_REGEXP }
  validates :password, confirmation: true, presence: true, on: :create
  validates :header_color, format: { with: HEADER_COLOR_VALIDATION }
  validates :avatar_url, format: { with: AVATAR_URL_VALIDATION }, on: :update, allow_blank: true
  
  has_many :questions, dependent: :destroy
  
  before_validation :format_username_to_downcase, :format_email_to_downcase
  before_save :encrypt_password
  
  scope :sorted, -> { order(username: :asc) }

  friendly_id :username, use: [:slugged, :history]

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def normalize_friendly_id(text)
    text.to_slug.transliterate(:russian).normalize.to_s
  end

  def should_generate_new_friendly_id?
    true
  end

  private

  def format_email_to_downcase
    self.email&.downcase!
  end

  def format_username_to_downcase
    self.username&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Доступ запрещен'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.friendly.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def question_params
      if current_user.present? &&
         params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end

    def authorize_user
      reject_user unless @question.user == current_user  
    end

    def check_captcha(model)
      current_user.present? || verify_recaptcha(model: model)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user.present?
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Вы успешно залогинились.'
    else
      flash.now.alert = 'Неправильный e-mail или пароль.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.sorted
    @hashtags = Hashtag.sorted
  end

  def new
    redirect_to root_url, alert: 'Вы уже вошли' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже вошли' if current_user.present?
    
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: "Вы успешно зарегистрировались." 
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_count = @questions.count
    @answered_questions_count = @questions.count(:answer)
    @unanswered_questions_count = @questions_count - @answered_questions_count
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Данные успешно обновлены." 
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Ваш аккаунт был удален."
  end

  private

  def authorize_user
    reject_user unless @user == current_user  
  end

  def load_user
    @user ||= User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url, :header_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.png'
    end
  end

  def inclination(amount, singular, singular_genitive, plural_genitive)
    if (amount % 100).between?(11, 14) 
      return "#{amount} #{plural_genitive}"
    end
    division_remainder = amount % 10
    if division_remainder == 1
      result = "#{amount} #{singular}"
    elsif division_remainder >= 2 && division_remainder <= 4
      result = "#{amount} #{singular_genitive}"
    else
      result = "#{amount} #{plural_genitive}"
    end
    return result
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>
 
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
      <div class="question-author">
        <% if question.author.present? %>
          автор вопроса:
          <%= link_to "#{question.author.name}", user_path(question.author) %>
        <% else %>
          анонимный вопрос
        <% end %>
      </div>
      
    </div>
    
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <% if question.hashtags %>
      <div class="question-in-hashtags">
        <% question.hashtags.each do |hashtag| %>
          <%= link_to hashtag.name, user_path(question.user) %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question), method: :delete, data: { confirm: 'Удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/hashtags/show.html.erb
 <div class="buffer-top"> 
  <div class="user-questions hastags-container">
    <h1>
      Вопросы с тегом <%= @hashtag.name %>
    </h1>
    <% @hashtag.questions.each do |q| %>
      <%= render partial: 'hashtags/question', object: q %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Good questions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  </head>

  <body>

    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title">
            <%= link_to "Хорошие вопросы", root_path %>
          </h1>
        </div>
        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %>
            <%= link_to 'Выйти', session_path, data: { method: :delete } %>
          <% else %>
            <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
            <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="content">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>
 
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>

      <div class="question-author">
        <% if question.author.present? %>
          автор вопроса:
          <%= link_to "#{question.author.name}", user_path(question.author) %>
        <% else %>
          анонимный вопрос
        <% end %>
      </div>
      
    </div>
    
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <% if question.hashtags %>
      <div class="question-in-hashtags">
        <% question.hashtags.each do |hashtag| %>
          <%= link_to hashtag.name, hashtag_path(hashtag) %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question), method: :delete, data: { confirm: 'Удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="content-wrapper buffer-both">
  <h1>Редактирование вопроса и ответа</h1>

  <%= render 'form', question: @question %>

</div>

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цветовая тема шапки вашего профиля', class: 'form-label' %>
        <%= f.text_field :header_color, class: 'jscolor form-text-field'%>
        
      </div>
      <div class="form-field">
        <%= button_tag 'Вернуть цвет по-умолчанию', id: 'reset_header_color', type: 'button', class: 'button button-dark button-small'%>
      </div>
      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>
    <%= link_to 'Удалить аккаунт', user_path(@user), method: :delete , class: 'button button-red button-small', data: { confirm: 'Вы точно хотите удалить аккаунт?'}%>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
  <div class="all-hashtags-block">
    <% @hashtags.each do |hashtag| %>
      <%= link_to hashtag.name, hashtag_path(hashtag) %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
    
      <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: #<%= @user.header_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <%= recaptcha_tags size: 'compact' unless current_user.present? %>
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="question-amount">
      Всего <%= inclination(@questions_count, 'вопрос', 'вопроса', 'вопросов') %>
      | отвечено на:
      <%= inclination(@answered_questions_count, 'вопрос', 'вопроса', 'вопросов') %>
      | не отвечено на:
      <%= inclination(@unanswered_questions_count, 'вопрос', 'вопроса', 'вопросов') %>
    </div>
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>